# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.11.0-bb28
PackageLocale: en-US
Publisher: Betterbird Project
PublisherUrl: https://www.betterbird.eu/
PublisherSupportUrl: https://www.betterbird.eu/support
PrivacyUrl: https://www.betterbird.eu/legal
PackageName: Betterbird
License: Mozilla Public License Version 2.0
LicenseUrl: https://www.mozilla.org/MPL/2.0
CopyrightUrl: https://www.betterbird.eu/legal
ShortDescription: Betterbird is a fork of Mozilla Thunderbird with additional features and bugfixes.
Moniker: betterbird
Tags:
- e-mail
- fork
- mail
- mozilla
- thunderbird
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://betterbird.eu/faq
ReleaseNotes: |
  NEW - Diacritics ignored in search (search, quick search, filters) - Bug 506064 Bug 1839085
  NEW - Linux: "Global Menubar" (Unity Menubar) now supported, set pref widget.gtk.global-menu.enabled.
  Known issue: The menus of the OpenPGP Key Manager window and the Calendar windows to create or edit events aren't made global.
  CHANGED - When folder had manually reordered subfolders, new subfolders are added semi-alphabetically after special folders.
  FIXED - Off-by-one pixel alignment of subject line in multi-line view
  FIXED - Improvements to feed subscribe dialog, OPML file third party import, feed drag/drop in folderpane and subscribe dialog 
ReleaseNotesUrl: https://www.betterbird.eu/releasenotes
ManifestType: defaultLocale
ManifestVersion: 1.6.0
