# Created with WinGet Automation using Komac v1.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Anaconda.Anaconda3
PackageVersion: '2023.07'
PackageLocale: en-US
Publisher: Anaconda, Inc.
PublisherUrl: https://www.anaconda.com
PrivacyUrl: https://www.anaconda.com/privacy-policy
Author: Anaconda, Inc.
PackageName: Anaconda3
PackageUrl: https://www.anaconda.com/products/individual
License: BSD 3-Clause License
LicenseUrl: https://docs.conda.io/en/latest/license.html
Copyright: (c) 2017 Continuum Analytics, Inc. (dba Anaconda, Inc.). https://www.anaconda.com. All Rights Reserved
CopyrightUrl: https://docs.conda.io/en/latest/license.html
ShortDescription: Python/R distribution for data science and machine learning, individual edition.
Tags:
- conda
- python
ManifestType: defaultLocale
ManifestVersion: 1.5.0
